name: Run Stablecoin Market Scraper Daily

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2 AM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Prevent infinite hangs
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          pip install requests

      # Step 4: Run the scraper script
      - name: Run stablecoins.py
        run: |
          python stablecoins.py
        env:
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}  # Use GitHub Secrets for API keys
