name: Run Stablecoin Market Scraper Daily

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2 AM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install Chrome and Chromedriver
      - name: Install Chrome and Chromedriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'

      # Step 4: Install Python dependencies
      - name: Install dependencies
        run: |
          pip install selenium requests

      # Step 5: Run the scraper script
      - name: Run stablecoins.py
        run: python stablecoins.py
