name: Run Python Scripts at 2 AM Daily

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2 AM every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify the Python version
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run stablecoins.py
        run: python stablecoins.py
